module.exports = [
    {
        path: '/',
        component: require('../views/demo/hello').Hello,
        name: 'hello',
        dm: 'hello',
    }, {
        path: '/simpleTree',
        component: require('../views/demo/simpleTree').SimpleTreeDemo,
        name: 'simpleTree',
        dm: 'simpleTree',
    }, {
        path: '/useIconfont',
        component: require('../views/demo/useIconfont').UseIconfont,
        name: 'useIconfont',
        dm: 'useIconfont',
    }, {
        path: '/matterCalendar',
        component: require('../views/demo/matterCalendar').MatterCalendarDemo,
        name: 'matterCalendar',
        dm: 'matterCalendar',
    }, {
        path: '/textareaNum',
        component: require('../views/demo/textareaNum').TextareaNumDemo,
        name: 'textareaNum',
        dm: 'textareaNum',
    }, {
        path: '/calendarSelect',
        component: require('../views/demo/calendarSelect').CalendarSelectDemo,
        name: 'calendarSelect',
        dm: 'calendarSelect',
    }, {
        path: '/inputSelect',
        component: require('../views/demo/inputSelect').InputSelectDemo,
        name: 'inputSelect',
        dm: 'inputSelect'
    }, {
        path: '/printA4',
        component: require('../views/demo/printA4').PrintA4Demo,
        name: 'printA4',
        dm: 'printA4'
    }, {
        path: '/printA4Table',
        component: require('../views/demo/printA4Table').PrintA4TableDemo,
        name: 'printA4Table',
        dm: 'printA4Table'
    }, {
        path: '/browser',
        component: require('../views/demo/browser').BrowserDemo,
        name: 'browser',
        dm: 'browser'
    }, {
        path: '/exTable',
        component: require('../views/demo/exTable').ExTableDemo,
        name: 'exTable',
        dm: 'exTable'
    }, {
        path: '/treeSelect',
        component: require('../views/demo/treeSelect').TreeSelectDemo,
        name: 'treeSelect',
        dm: 'treeSelect'
    }, {
        path: '/lazyLoad',
        component: require('../views/demo/lazyLoad').LazyLoadDemo,
        name: 'lazyLoad',
        dm: 'lazyLoad'
    }, {
        path: '/toggleModal',
        component: require('../views/demo/toggleModal').ToggleModalDemo,
        name: 'toggleModal',
        dm: 'toggleModal'
    }, {
        path: '/drawerLayout',
        component: require('../views/demo/drawerLayout').DrawerLayoutDemo,
        name: 'drawerLayout',
        dm: 'drawerLayout'
    }, {
        path: '/drag',
        component: require('../views/demo/drag').DragDemo,
        name: 'drag',
        dm: 'drag'
    }, {
        path: '/handleEvents',
        component: require('../views/demo/handleEvents').HandleEventsDemo,
        name: 'handleEvents',
        dm: 'handleEvents'
    }, {
        path: '/handleNumber',
        component: require('../views/demo/handleNumber').HandleNumberDemo,
        name: 'handleNumber',
        dm: 'handleNumber'
    }, {
        path: '/handleReg',
        component: require('../views/demo/handleReg').HandleRegDemo,
        name: 'handleReg',
        dm: 'handleReg'
    }, {
        path: '/handleDate',
        component: require('../views/demo/handleDate').HandleDateDemo,
        name: 'handleDate',
        dm: 'handleDate'
    }, {
        path: '/sortButton',
        component: require('../views/demo/sortButton').SortButtonDemo,
        name: 'sortButton',
        dm: 'sortButton'
    }, {
        path: '/rangePicker',
        component: require('../views/demo/rangePicker').RangePickerDemo,
        name: 'rangePicker',
        dm: 'rangePicker'
    }, {
        path: '/dateRange',
        component: require('../views/demo/dateRange').DateRangeDemo,
        name: 'dateRange',
        dm: 'dateRange'
    }
];